name: R-Nacos
logo: https://r-nacos.github.io/docs/logo.svg
author: R-Nacos
description: Rust 语言实现的 Nacos 服务平台，兼容 Nacos(Java)，启动更快、占用系统资源更小（初始内存小于10M）、性能更高、运行更稳定的服务。
category: development
platform: other
homepage: https://github.com/nacos-group/r-nacos
version: 0.7.10
url:
  via GitHub Release: https://github.com/nacos-group/r-nacos/releases/latest
  via Docker: https://hub.docker.com/r/qingpan/rnacos
script:
  args:
    autoupdate:
      via GitHub Release: https://github.com/nacos-group/r-nacos/releases/latest
      via Docker: https://hub.docker.com/r/qingpan/rnacos
  name: appfork-check-update
