author: Mountain Loop Labs
name: Yaak
logo: https://yaak.app/static/logo.svg
description: A fast, privacy-first API client for REST, GraphQL, SSE, WebSocket, and
  gRPC â€“ built with Tauri, Rust, and React.
category: development
version: 2025.9.3
platform: windows
script:
  args:
    url: github://mountain-loop/yaak
    autoupdate:
    - https://github.com/mountain-loop/yaak/releases/download/v${version}/Yaak_${version}_x64-setup_windows.exe
  name: appfork-check-update
url:
- https://github.com/mountain-loop/yaak/releases/download/v2025.9.3/Yaak_2025.9.3_x64-setup_windows.exe
homepage: https://yaak.app
