name: Tailscale
logo: https://tailscale.com/favicon.png
author: Tailscale Inc.
description: Tailscale a WireGuard based mesh VPN, used to connect your computers and other devices together securely without proxies.
category: network
platform: android
homepage: https://tailscale.com
version: 1.94.1
url:
  - https://pkgs.tailscale.com/stable/tailscale-android-universal-1.94.1.apk
script:
  args:
    url: https://pkgs.tailscale.com/stable/
    regex: tailscale-android-universal-(?<version>[\d.]+)\.apk
    autoupdate:
      - https://pkgs.tailscale.com/stable/tailscale-android-universal-${version}.apk
  name: appfork-check-update
