name: MetaCubeXD
author: MetaCubeX
logo: https://raw.githubusercontent.com/MetaCubeX/metacubexd/refs/heads/main/public/favicon.svg
description: Mihomo Dashboard, The Official One, XD
category: network
platform: other
homepage: https://github.com/MetaCubeX/metacubexd
version: 1.235.0
url:
  compressed-dist.tgz: https://github.com/MetaCubeX/metacubexd/releases/download/v1.235.0/compressed-dist.tgz
  Official: https://d.metacubex.one
  GH Pages: https://metacubex.github.io/metacubexd
  Cloudflare Pages: https://metacubexd.pages.dev
script:
  args:
    autoupdate:
      compressed-dist.tgz: https://github.com/MetaCubeX/metacubexd/releases/download/v${version}/compressed-dist.tgz
      Official: https://d.metacubex.one
      GH Pages: https://metacubex.github.io/metacubexd
      Cloudflare Pages: https://metacubexd.pages.dev
  name: appfork-check-update
