author: 福州猿力信息科技有限公司
name: uTools
logo: https://www.u-tools.cn/assets/favicon.png
description: 新一代效率工具平台，自由组合插件应用，打造专属你的趁手工具集。支持macOS 10.15+
category: tools
version: 7.5.0
platform: mac
url:
- https://open.u-tools.cn/download/uTools-7.5.0.dmg
- https://open.u-tools.cn/download/uTools-7.5.0-arm64.dmg
homepage: https://www.u-tools.cn
script:
  args:
    regex: uTools-([\d.]+)(?:-arm64)?\.dmg
    autoupdate:
    - https://open.u-tools.cn/download/uTools-${version}.dmg
    - https://open.u-tools.cn/download/uTools-${version}-arm64.dmg
    url: https://www.u-tools.cn/download/
  name: appfork-check-update
