author: Astral
name: uv
logo: https://docs.astral.sh/uv/assets/logo-letter.svg
description: An extremely fast Python package and project manager, written in Rust.
category: development
version: 0.9.27
platform: windows
url:
  - https://github.com/astral-sh/uv/releases/download/0.9.27/uv-x86_64-pc-windows-msvc.zip
  - https://github.com/astral-sh/uv/releases/download/0.9.27/uv-aarch64-pc-windows-msvc.zip
homepage: https://github.com/astral-sh/uv
script:
  args:
    autoupdate:
      - https://github.com/astral-sh/uv/releases/download/${version}/uv-x86_64-pc-windows-msvc.zip
      - https://github.com/astral-sh/uv/releases/download/${version}/uv-aarch64-pc-windows-msvc.zip
  name: appfork-check-update
