author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2026-01-09 00:00:00 (1767888000)
platform: other
url:
  'Total War: THREE KINGDOMS [2026-01-09 00:00:00]': https://store.epicgames.com/zh-CN/p/total-war-three-kingdoms-d3bb7a
homepage: https://store.epicgames.com/zh-CN/free-games
