author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2026-02-20 00:00:00 (3543033600)
platform: other
url:
  暗面侦探：黑暗中的摸索 [2026-02-20 00:00:00]: https://store.epicgames.com/zh-CN/p/the-darkside-detective-a-fumble-in-the-dark-174fcf
  Nobody Wants to Die [2026-02-20 00:00:00]: https://store.epicgames.com/zh-CN/p/nobody-wants-to-die-fe21cd
homepage: https://store.epicgames.com/zh-CN/free-games
