author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2025-12-22 00:00:00 (1766332800)
platform: other
url:
  Blood West [2025-12-22 00:00:00]: https://store.epicgames.com/zh-CN/p/blood-west-8f6ffd
homepage: https://store.epicgames.com/zh-CN/free-games
