author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2025-12-30 00:00:00 (1767024000)
platform: other
url:
  SKALD Against the Black Priory [2025-12-30 00:00:00]: https://store.epicgames.com/zh-CN/p/skald-against-the-black-priory-cffcc0
homepage: https://store.epicgames.com/zh-CN/free-games
