author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2026-01-23 00:00:00 (3538195200)
platform: other
url:
  'Styx: Master of Shadows [2026-01-23 00:00:00]': https://store.epicgames.com/zh-CN/p/styx-master-of-shadows-4d9ab3
  'Styx: Shards of Darkness - Deluxe Edition [2026-01-23 00:00:00]': https://store.epicgames.com/zh-CN/p/styx-shards-of-darkness-77c030
homepage: https://store.epicgames.com/zh-CN/free-games
