author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2025-11-14 00:00:00 (3526099200)
platform: other
url:
  《Idle Champions of the Forgotten Realms》 [2025-11-14 00:00:00]: https://store.epicgames.com/zh-CN/p/idle-champions-of-the-forgotten-realms
  Felix The Reaper [2025-11-14 00:00:00]: https://store.epicgames.com/zh-CN/p/felix-the-reaper-3f7e62
homepage: https://store.epicgames.com/zh-CN/free-games
