author: Epic Games
name: Epic商城喜加一
description: Epic今天又送什么游戏了？此处的版本号即为赠送的游戏中最晚截止领取时间（北京时间UTC+8），快点击下方按钮进入商城页面领取吧！
category: games
version: 2025-11-21 00:00:00 (5290963200)
platform: other
url:
  《灾厄逆刃》 [2025-11-21 00:00:00]: https://store.epicgames.com/zh-CN/p/scourgebringer
  寂静之歌 [2025-11-21 00:00:00]: https://store.epicgames.com/zh-CN/p/songs-of-silence-778d86
  Zero Hour [2025-11-21 00:00:00]: https://store.epicgames.com/zh-CN/p/zero-hour-8449a0
homepage: https://store.epicgames.com/zh-CN/free-games
