name: opencode
author: Anomaly
logo: https://opencode.ai/favicon-96x96-v3.png
description: The open source AI coding agent.
homepage: https://opencode.ai
category: development
version: 1.2.7
platform: windows
url:
  - https://github.com/anomalyco/opencode/releases/download/v1.2.7/opencode-windows-x64.zip
  - https://github.com/anomalyco/opencode/releases/download/v1.2.7/opencode-desktop-windows-x64.exe
script:
  name: appfork-check-update
  args:
    url: github://anomalyco/opencode
    autoupdate:
      - https://github.com/anomalyco/opencode/releases/download/v${version}/opencode-windows-x64.zip
      - https://github.com/anomalyco/opencode/releases/download/v${version}/opencode-desktop-windows-x64.exe
